Add controllers
Deathriot/java-shareit pull request #1
Opened 2024-05-27 19:07 UTC by Deathriot

Погнали!

2024-05-28 15:03 UTC, LexLippi requested changes
Привет!

Неплохая работа!

Есть некоторое количество замечаний, которые необходимо исправить!

Желаю удачи!

2024-05-28 15:03 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/item/dto/ItemMapper.java
> +public class ItemMapper {
Это класс-помощник, стоит привести его к стандартной реализации:

https://www.baeldung.com/java-helper-vs-utility-classes

2024-05-28 15:03 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/user/UserRepository.java
> +    Map<Long, String> getEmails();
Не стоит возвращать `Map`. Стоит проводить обработку внутри хранилища, например передавать `email` и `userId`, возвращать `boolean` есть ли другой пользователь с таким `email`.

Передавать копию `Map` может быть накладной операцией, а передавать нужно именно копию, чтобы соблюдать инкапсуляцию

2024-05-28 15:03 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/user/dto/UserMapper.java
> +public class UserMapper {
Про такие классы уже писал

2024-05-28 20:52 UTC, Deathriot commented on src/main/java/ru/practicum/shareit/exception/ErrorResponse.java
> +    private final String massage;
зря вы от массажа отказываетесь..

2024-05-29 06:51 UTC, LexLippi commented
Привет!

Хорошая работа!

Желаю удачи в следующих спринтах!

2024-05-29 19:45 UTC, merged