Feat: Добавлена возможность бронирования, данные теперь хранятся в БД
Deathriot/java-shareit pull request #2
Opened 2024-06-05 18:04 UTC by Deathriot

Пожалуйста не жестите, у меня 5 дней чтоб сдать еще 2 спринта...

2024-06-06 13:30 UTC, LexLippi requested changes
Привет!

Неплохая работа!

Есть некоторое количество замечаний, которые необходимо исправить!

Желаю удачи!

2024-06-06 13:30 UTC, LexLippi commented on src/main/resources/schema.sql
> +DROP ALL OBJECTS;
Вот этой строчки быть не должно.
Ни один пользователь не захочет использовать программу, в которой постоянно удаляются его данные

2024-06-06 13:30 UTC, LexLippi commented on src/main/resources/schema.sql
> +  EMAIL     VARCHAR(64) NOT NULL,
По RFC максимальная длина `email` составляет 256 символов, то есть не все валидные `email` влезут в это поле.

https://stackoverflow.com/questions/386294/what-is-the-maximum-length-of-a-valid-email-address

2024-06-06 13:30 UTC, LexLippi commented on src/main/resources/schema.sql
> +  AVAILABLE     BOOLEAN,
Может быть `null`?

2024-06-06 13:30 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/request/model/ItemRequest.java
>  public class ItemRequest {
Почему это теперь пустой класс?

2024-06-06 13:30 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +                throw new UnSupportedStateException("Unknown state: " + String.valueOf(state));
`UnsupportedStateException`

2024-06-06 14:56 UTC, Deathriot commented on src/main/java/ru/practicum/shareit/request/model/ItemRequest.java
>  public class ItemRequest {
это болванка, ведь его надо будет использовать только в следующих ТЗ

2024-06-08 09:02 UTC, LexLippi commented
Привет!

Отличная работа!

Желаю удачи в следующих спринтах!

2024-06-08 11:16 UTC, merged